version: "3"
services:
    pythonrng:
        build: ./python
        ports:
          - "8080:8000"
        networks:
          - webnet
    router:
        build: ./nginx
        ports:
          - "80:80"
        networks:
          - webnet
networks:
    webnet:
